# Generated by Django 2.1.7 on 2019-04-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='seller_id',
            field=models.IntegerField(blank=True, default=13),
            preserve_default=False,
        ),
    ]
